[package]
name = "advent_of_code_2025_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0"
paste = "1.0"
rayon = "1.11"
ndarray = { version = "0.17", features = ["rayon"] }
disjoint = "0.8"
bitvec = "1.0"
microlp = "0.2"
petgraph = "0.8"
